# Modul 7: 
**Topik:**

- Pengenalan NumPy

Diberikan data kumpulan koordinat pada ruang dua dimensi:

```python
A = np.array([[1, 2],
              [2, 4],
              [0, 6]])

B = np.array([[3, 2],
              [2, 5],
              [1, 6],
              [5, 5]])
```
Buatlah NumPy Array baru bernama `dist`:
```python
dist = np.zeros([A.shape[0], B.shape[0]])
```
Isi dari array `dist` adalah jarak (norm) dari 1 titik ke titik-titik lainnya:

| $\|A_0-B_0\|$ | $\|A_0-B_1\|$ | $\|A_0-B_2\|$ | $\|A_0-B_3\|$ |
| ------------- | ------------- | ------------- | ------------- |
| $\|A_1-B_0\|$ | $\|A_1-B_1\|$ | $\|A_1-B_2\|$ | $\|A_1-B_3\|$ |
| $\|A_2-B_0\|$ | $\|A_2-B_1\|$ | $\|A_2-B_3\|$ | $\|A_2-B_3\|$ |


1. Buatlah program Python untuk menghitung isi `dist` di atas dimana Anda harus tepat menggunakan:
	- dua buah for loop
	- 1 buah for loop
	- tanpa for loop

2. Buat menjadi 3 buah fungsi, lalu ujilah dengan array dua dimensi dengan jumlah elemen jauh lebih besar.

## Soal 1

In [35]:
import numpy as np

A = np.array([[1, 2],
              [2, 4],
              [0, 6]])

B = np.array([[3, 2],
              [2, 5],
              [1, 6],
              [5, 5]])

### Dengan 2 buah for-loop

In [36]:
dist = np.zeros((A.shape[0], B.shape[0]))

for i in range(A.shape[0]):
    for j in range(B.shape[0]):
        dist[i,j] = (np.linalg.norm(A[i,:] - B[j,:]))

In [37]:
dist

array([[2.        , 3.16227766, 4.        , 5.        ],
       [2.23606798, 1.        , 2.23606798, 3.16227766],
       [5.        , 2.23606798, 1.        , 5.09901951]])

###  Dengan 1 buah for-loop

In [38]:
dist = np.zeros((A.shape[0], B.shape[0]))

for i in range(A.shape[0]):
    dist[i, :] = np.linalg.norm(A[i,:]-B, axis=1)

In [39]:
dist

array([[2.        , 3.16227766, 4.        , 5.        ],
       [2.23606798, 1.        , 2.23606798, 3.16227766],
       [5.        , 2.23606798, 1.        , 5.09901951]])

### Tanpa for-loop

In [40]:
SA = (A**2).sum(axis=1, keepdims=True)
SB = (B**2).sum(axis=1, keepdims=True)

dist = np.sqrt(SA+SB.T-2*(A@B.T))


In [41]:
dist

array([[2.        , 3.16227766, 4.        , 5.        ],
       [2.23606798, 1.        , 2.23606798, 3.16227766],
       [5.        , 2.23606798, 1.        , 5.09901951]])

## Soal 2

In [42]:
def dua_loop(A, B):
    dist = np.zeros((A.shape[0], B.shape[0]))

    for i in range(A.shape[0]):
        for j in range(B.shape[0]):
            dist[i,j] = (np.linalg.norm(A[i,:] - B[j,:]))

    return dist

In [43]:
def satu_loop(A, B):
    dist = np.zeros((A.shape[0], B.shape[0]))

    for i in range(A.shape[0]):
        dist[i, :] = np.linalg.norm(A[i,:]-B, axis=1)

    return dist

In [44]:
def tanpa_loop(A, B):
    SA = (A*A).sum(axis=1, keepdims=True)
    SB = (B*B).sum(axis=1, keepdims=True)

    dist = np.sqrt(SA+SB.T-2*(A@B.T))

    return dist

### Testing

In [45]:
A = np.random.rand(1000, 2)
B = np.random.rand(2000, 2)

In [51]:
import time

start = time.time()
R1 = dua_loop(A, B)
end = time.time()
print(end - start)

18.593506813049316


In [47]:
start = time.time()
R2 =satu_loop(A, B)
end = time.time()
print(end - start)

0.11231708526611328


In [48]:
start = time.time()
R3 = tanpa_loop(A, B)
end = time.time()
print(end - start)

0.036864519119262695


In [49]:
np.allclose(R1,R2)

True

In [50]:
np.allclose(R1,R3)

True